name: Python Dependency and Vulnerability Check

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - test

jobs:
  Python-check:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install Python tools
      - name: Install Python tools
        run: |
          python -m pip install --upgrade pip
          pip install pip-review safety

      # Check Python outdated packages
      - name: Check Python outdated packages
        run: |
          pip-review --local --outdated > python_outdated.txt || true
          cat python_outdated.txt
          if [ -s python_outdated.txt ]; then
            echo "Outdated Python packages detected with latest versions available:"
            cat python_outdated.txt
          else
            echo "All Python packages are up to date."
          fi

      # Run Safety CLI to check for vulnerabilities and save the output in a JSON file
      - name: Run Safety CLI to check for vulnerabilities
        run: |
          safety --key 81919e15-f76a-4b4e-a0cf-aa27f74a31b1 scan --detailed-output --save-as json results.json || true

      # Parse the Safety scan results and check for vulnerabilities
      - name: Parse and check vulnerabilities from Safety scan
        run: |
          echo "Vulnerability scan results:"
          # Extract and count the number of vulnerabilities found in the 'dependencies' section
          vulnerabilities_count=$(jq '[.scan_results.files[].results.dependencies[].vulnerabilities.known_vulnerabilities | length] | add' results.json)
          
          # If any vulnerabilities are found, exit with status 1
          if [ "$vulnerabilities_count" -gt 0 ]; then
            echo "Vulnerabilities found! Exiting with status 1."
            jq '.scan_results.files[].results.dependencies[].vulnerabilities' results.json
            exit 1
          else
            echo "No vulnerabilities found."
          fi
